version: '3.9'

services:
  app:
    build:
      context: .
      target: release
    restart: always
    environment:
      PORT: "${PORT}"
      LOG_DISABLED: 'false'
      JWT_SECRET: '${JWT_SECRET}'
      MONGO_URI: '${MONGO_URI}'
      VIRTUAL_HOST: api.loca.kimjisub.me
      LETSENCRYPT_HOST: api.loca.kimjisub.me
    depends_on:
      - mongo
    networks:
      - default
      - proxy

  mongo:
    image: mongo
    networks:
      - default

networks:
  default:
  proxy:
    external: true
    name: proxy