version: '3.8'

services:
  app:
    build:
      context: .
      target: release
    restart: always
    environment:
      PORT: '80'
      LOG_DISABLED: 'false'
      JWT_SECRET: '0development0'
      MONGO_URI: 'mongodb://mongo:27017/loca'
      VIRTUAL_HOST: api.loca.kimjisub.me
      LETSENCRYPT_HOST: api.loca.kimjisub.me
    depends_on:
      - mongo
    networks:
      - default
      - bridge
  mongo:
    image: mongo

networks:
  bridge:
    driver: bridge